In [54]:
import numpy as np
import pandas as pd

In [3]:
books = pd.read_csv('Books.csv')

C:\Users\ersah\AppData\Local\Temp\ipykernel_30920\679519066.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv('Books.csv')

In [4]:
users = pd.read_csv('Users.csv')
ratings = pd.read_csv('Ratings.csv')

In [5]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [6]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [7]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [8]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

#### Checking missing values

In [9]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            1
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [10]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [11]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

#### Checking duplicate values

In [13]:
books.duplicated().sum()

0

In [14]:
users.duplicated().sum()

0

In [15]:
ratings.duplicated().sum()

0

## Popularity Based Recommender System

In [16]:
# We will consider top 250 books based on ratings. In case of a tie, minimum 250 ratings on a book will be considered

In [17]:
ratings

         User-ID         ISBN  Book-Rating
0         276725   034545104X            0
1         276726   0155061224            5
2         276727   0446520802            0
3         276729   052165615X            3
4         276729   0521795028            6
...          ...          ...          ...
1149775   276704   1563526298            9
1149776   276706   0679447156            0
1149777   276709   0515107662           10
1149778   276721   0590442449           10
1149779   276723  05162443314            8

[1149780 rows x 3 columns]

In [18]:
books

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...,...,...,...,...
271355,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...
271356,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...
271357,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...
271358,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...
271359,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...

##### Merging 'books' & 'ratings' table on top of ISBN

In [24]:
ratings_with_name = ratings.merge(books , on = 'ISBN' )

In [25]:
ratings_with_name.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...

In [35]:
num_rating_df =ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()

In [36]:
num_rating_df

                                               Book-Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [37]:
num_rating_df.rename(columns={'Book-Rating':'num_ratings'} , inplace=True)
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [38]:
avg_rating_df =ratings_with_name.groupby('Book-Title').mean()['Book-Rating'].reset_index()

In [40]:
avg_rating_df.rename(columns={'Book-Rating':'avg_rating'},inplace=True)
avg_rating_df

                                               Book-Title  avg_rating
0        A Light in the Storm: The Civil War Diary of ...    2.250000
1                                   Always Have Popsicles    0.000000
2                    Apple Magic (The Collector's series)    0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...    8.000000
4        Beyond IBM: Leadership Marketing and Finance ...    0.000000
...                                                   ...         ...
241066                                      Ã?Â?lpiraten.    0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.    5.250000
241068                                Ã?Â?sterlich leben.    7.000000
241069                              Ã?Â?stlich der Berge.    2.666667
241070                                  Ã?Â?thique en toc    4.000000

[241071 rows x 2 columns]

In [41]:
popularity_df = num_rating_df.merge(avg_rating_df , on='Book-Title')
popularity_df

,Book-Title,num_ratings,avg_rating
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [50]:
popularity_df = popularity_df[popularity_df['num_ratings']>=250].sort_values('avg_rating' , ascending=False).head(50)

In [53]:
popularity_df.merge(books , on ='Book-Title').drop_duplicates('Book-Title')

,Book-Title,num_ratings,avg_rating,ISBN,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804,0439136350,J. K. Rowling,1999,Scholastic,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...,http://images.amazon.com/images/P/0439136350.0...
3,Harry Potter and the Goblet of Fire (Book 4),387,5.824289,0439139597,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...,http://images.amazon.com/images/P/0439139597.0...
5,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410,0590353403,J. K. Rowling,1998,Scholastic,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...,http://images.amazon.com/images/P/0590353403.0...
9,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441,043935806X,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...,http://images.amazon.com/images/P/043935806X.0...
13,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453,0439064872,J. K. Rowling,2000,Scholastic,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...,http://images.amazon.com/images/P/0439064872.0...
16,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117,0345339681,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339681.0...,http://images.amazon.com/images/P/0345339681.0...,http://images.amazon.com/images/P/0345339681.0...
17,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370,0345339703,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339703.0...,http://images.amazon.com/images/P/0345339703.0...,http://images.amazon.com/images/P/0345339703.0...
26,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652,059035342X,J. K. Rowling,1999,Arthur A. Levine Books,http://images.amazon.com/images/P/059035342X.0...,http://images.amazon.com/images/P/059035342X.0...,http://images.amazon.com/images/P/059035342X.0...
28,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769,0345339711,J.R.R. TOLKIEN,1986,Del Rey,http://images.amazon.com/images/P/0345339711.0...,http://images.amazon.com/images/P/0345339711.0...,http://images.amazon.com/images/P/0345339711.0...
39,To Kill a Mockingbird,510,4.700000,0446310786,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
47,The Da Vinci Code,898,4.642539,0385504209,Dan Brown,2003,Doubleday,http://images.amazon.com/images/P/0385504209.0...,http://images.amazon.com/images/P/0385504209.0...,http://images.amazon.com/images/P/0385504209.0...
53,The Five People You Meet in Heaven,430,4.551163,0786868716,Mitch Albom,2003,Hyperion,http://images.amazon.com/images/P/0786868716.0...,http://images.amazon.com/images/P/0786868716.0...,http://images.amazon.com/images/P/0786868716.0...
55,The Catcher in the Rye,449,4.545657,0316769487,J.D. Salinger,1991,"Little, Brown",http://images.amazon.com/images/P/0316769487.0...,http://images.amazon.com/images/P/0316769487.0...,http://images.amazon.com/images/P/0316769487.0...
62,The Lovely Bones: A Novel,1295,4.468726,0316666343,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...,http://images.amazon.com/images/P/0316666343.0...,http://images.amazon.com/images/P/0316666343.0...
63,1984,284,4.454225,0451524934,George Orwell,1990,Signet Book,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...,http://images.amazon.com/images/P/0451524934.0...
72,Prodigal Summer: A Novel,253,4.450593,0060959037,Barbara Kingsolver,2001,Perennial,http://images.amazon.com/images/P/0060959037.0...,http://images.amazon.com/images/P/0060959037.0...,http://images.amazon.com/images/P/0060959037.0...
73,Neverwhere,265,4.449057,0380789019,Neil Gaiman,1998,Avon,http://images.amazon.com/images/P/0380789019.0...,http://images.amazon.com/images/P/0380789019.0...,http://images.amazon.com/images/P/0380789019.0...
78,The Secret Life of Bees,774,4.447028,0142001740,Sue Monk Kidd,2003,Penguin Books,http://images.amazon.com/images/P/0142001740.0...,http://images.amazon.com/images/P/0142001740.0...,http://images.amazon.com/images/P/0142001740.0...
84,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890,0060392452,Michael Moore,2002,Regan Books,http://images.amazon.com/images/P/0060392452.0...,http://images.amazon.com/images/P/0060392452.0...,http://images.amazon.com/images/P/0060392452.0...
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970,0385484518,MITCH ALBOM,1997,Doubleday,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...,http://images.amazon.com/images/P/0385484518.0...
88,The Red Tent (Bestselling Backlist),723,4.334716,0312195516,Anita Diamant,1998,Picador USA,http://images.amazon.com/images/P/0312195516.0...,http://images.amazon.com/images/P/0312195516.0...,http://images.amazon.com/images/P/0312195516.0...
89,The Hitchhiker's Guide to the Galaxy,268,4.328358,0671461494,Douglas Adams,1982,Pocket,http://images.amazon.com/images/P/0671461494.0...,http://images.amazon.com/images/P/0671461494.0...,http://images.amazon.com/images/P/0671461494.0...
98,Nickel and Dimed: On (Not) Getting By in America,335,4.289552,0805063897,Barbara Ehrenreich,2002,Owl Books,http://images.amazon.com/images/P/0805063897.0...,http://images.amazon.com/images/P/0805063897.0...,http://images.amazon.com/images/P/0805063897.0...
100,Into the Wild,252,4.273810,0385486804,Jon Krakauer,1997,Anchor,http://images.amazon.com/images/P/0385486804.0...,http://images.amazon.com/images/P/0385486804.0...,http://images.amazon.com/images/P/0385486804.0...
103,Fahrenheit 451,409,4.264059,3257208626,Ray Bradbury,1994,Distribooks Inc,http://images.amazon.com/images/P/3257208626.0...,http://images.amazon.com/images/P/3257208626.0...,http://images.amazon.com/images/P/3257208626.0...
116,Girl with a Pearl Earring,526,4.218631,0452282152,Tracy Chevalier,2001,Plume Books,http://images.amazon.com/images/P/0452282152.0...,http://images.amazon.com/images/P/0452282152.0...,http://images.amazon.com/images/P/0452282152.0...
117,Outlander,283,4.173145,0440222915,DIANA GABALDON,1996,Dell,http://images.amazon.com/images/P/0440222915.0...,http://images.amazon.com/images/P/0440222915.0...,http://images.amazon.com/images/P/0440222915.0...
123,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983,0446672211,Billie Letts,1998,Warner Books,http://images.amazon.com/images/P/0446672211.0...,http://images.amazon.com/images/P/0446672211.0...,http://images.amazon.com/images/P/0446672211.0...
124,Seabiscuit: An American Legend,275,4.098182,0449005615,LAURA HILLENBRAND,2002,Ballantine Books,http://images.amazon.com/images/P/0449005615.0...,http://images.amazon.com/images/P/0449005615.0...,http://images.amazon.com/images/P/0449005615.0...
126,Life of Pi,664,4.088855,0151008116,Yann Martel,2002,Harcourt,http://images.amazon.com/images/P/0151008116.0...,http://images.amazon.com/images/P/0151008116.0...,http://images.amazon.com/images/P/0151008116.0...
130,The Bean Trees,389,4.087404,0060915544,Barbara Kingsolver,1989,Perennial,http://images.amazon.com/images/P/0060915544.0...,http://images.amazon.com/images/P/0060915544.0...,http://images.amazon.com/images/P/0060915544.0...
133,"A Child Called \It\"": One Child's Courage to S...",265,4.086792,1558743669,Dave Pelzer,1995,Health Communications,http://images.amazon.com/images/P/1558743669.0...,http://images.amazon.com/images/P/1558743669.0...,http://images.amazon.com/images/P/1558743669.0...
135,ANGELA'S ASHES,279,4.075269,0684874350,Frank McCourt,1996,Scribner,http://images.amazon.com/images/P/0684874350.0...,http://images.amazon.com/images/P/0684874350.0...,http://images.amazon.com/images/P/0684874350.0...
137,Good in Bed,490,4.055102,0743418174,Jennifer Weiner,2002,Washington Square Press,http://images.amazon.com/images/P/0743418174.0...,http://images.amazon.com/images/P/0743418174.0...,http://images.amazon.com/images/P/0743418174.0...
139,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383,0060938455,Eric Schlosser,2002,Perennial,http://images.amazon.com/images/P/0060938455.0...,http://images.amazon.com/images/P/0060938455.0...,http://images.amazon.com/images/P/0060938455.0...
140,American Gods,302,4.006623,0380789035,Neil Gaiman,2002,HarperTorch,http://images.amazon.com/images/P/0380789035.0...,http://images.amazon.com/images/P/0380789035.0...,http://images.amazon.com/images/P/0380789035.0...
141,Skipping Christmas,322,4.006211,0385505833,JOHN GRISHAM,2001,Doubleday,http://images.amazon.com/images/P/0385505833.0...,http://images.amazon.com/images/P/0385505833.0...,http://images.amazon.com/images/P/0385505833.0...
147,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145,0842329129,Tim Lahaye,1996,Tyndale House Publishers,http://images.amazon.com/images/P/0842329129.0...,http://images.amazon.com/images/P/0842329129.0...,http://images.amazon.com/images/P/0842329129.0...
149,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000,037582345X,PHILIP PULLMAN,2002,Knopf Books for Young Readers,http://images.amazon.com/images/P/037582345X.0...,http://images.amazon.com/images/P/037582345X.0...,http://images.amazon.com/images/P/037582345X.0...
157,The Color Purple,314,3.964968,0671617028,Alice Walker,1985,Pocket Books,http://images.amazon.com/images/P/0671617028.0...,http://images.amazon.com/images/P/0671617028.0...,http://images.amazon.com/images/P/0671617028.0...
163,Silence of the Lambs,256,3.960938,0312924585,Thomas Harris,1991,St. Martin's Press,http://images.amazon.com/images/P/0312924585.0...,http://images.amazon.com/images/P/0312924585.0...,http://images.amazon.com/images/P/0312924585.0...
166,About a Boy,262,3.900763,1573227331,Nick Hornby,1999,Riverhead Books,http://images.amazon.com/images/P/1573227331.0...,http://images.amazon.com/images/P/1573227331.0...,http://images.amazon.com/images/P/1573227331.0...
173,Seven Up (A Stephanie Plum Novel),278,3.888489,0312265840,Janet Evanovich,2001,St. Martin's Press,http://images.amazon.com/images/P/0312265840.0...,http://images.amazon.com/images/P/0312265840.0...,http://images.amazon.com/images/P/0312265840.0...
175,The Alchemist: A Fable About Following Your Dream,266,3.875940,0062502174,Paulo Coelho,1993,HarperSanFrancisco,http://images.amazon.com/images/P/0062502174.0...,http://images.amazon.com/images/P/0062502174.0...,http://images.amazon.com/images/P/0062502174.0...
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,269,3.825279,0312983867,Janet Evanovich,2003,St. Martin's Paperbacks,http://images.amazon.com/images/P/0312983867.0...,http://images.amazon.com/images/P/0312983867.0...,http://images.amazon.com/images/P/0312983867.0...
182,Suzanne's Diary for Nicholas,457,3.820569,0316969443,James Patterson,2001,"Little, Brown",http://images.amazon.com/images/P/0316969443.0...,http://images.amazon.com/images/P/0316969443.0...,http://images.amazon.com/images/P/0316969443.0...
186,Lord of the Flies,259,3.818533,0399501487,William Gerald Golding,1959,Perigee Trade,http://images.amazon.com/images/P/0399501487.0...,http://images.amazon.com/images/P/0399501487.0...,http://images.amazon.com/images/P/0399501487.0...
192,A Prayer for Owen Meany,413,3.796610,0345361792,John Irving,1990,Ballantine Books,http://images.amazon.com/images/P/0345361792.0...,http://images.amazon.com/images/P/0345361792.0...,http://images.amazon.com/images/P/0345361792.0...
194,"The Vampire Lestat (Vampire Chronicles, Book II)",301,3.777409,0345313860,ANNE RICE,1986,Ballantine Books,http://images.amazon.com/images/P/0345313860.0...,http://images.amazon.com/images/P/0345313860.0...,http://images.amazon.com/images/P/0345313860.0...
195,White Oleander : A Novel (Oprah's Book Club),356,3.772472,0316284955,Janet Fitch,2000,Back Bay Books,http://images.amazon.com/images/P/0316284955.0...,http://images.amazon.com/images/P/0316284955.0...,http://images.amazon.com/images/P/0316284955.0...

## Collaborative Based Filtering

In [94]:
# We will create a table in which columns will have user attribute while rows will have book attribute.

# The intersection of a column and row will indicate the rating done on a book by a user

# For this model, we will consider only those users who have done a minimum of 200 ratings(experienced user)

# We will consider only those books on which minimum 50 ratings have been done(not considering unpopular books)

In [104]:
ratings_with_name.groupby('Book-Title').sum().reset_index()

,Book-Title,User-ID,Book-Rating
0,A Light in the Storm: The Civil War Diary of ...,207229,9
1,Always Have Popsicles,172742,0
2,Apple Magic (The Collector's series),198711,0
3,"Ask Lily (Young Women of Faith: Lily Series, ...",269557,8
4,Beyond IBM: Leadership Marketing and Finance ...,11601,0
...,...,...,...
241066,Ã?Â?lpiraten.,201065,0
241067,Ã?Â?rger mit Produkt X. Roman.,466918,21
241068,Ã?Â?sterlich leben.,256636,7
241069,Ã?Â?stlich der Berge.,595492,8
241070,Ã?Â?thique en toc,79064,8

In [115]:
x = ratings_with_name.groupby('User-ID').count()['Book-Rating'] > 200
u200 = x[x].index

In [118]:
filtered_rating = ratings_with_name[ratings_with_name['User-ID'].isin(u200)]

In [120]:
filtered_rating.columns

Index(['User-ID', 'ISBN', 'Book-Rating', 'Book-Title', 'Book-Author',
       'Year-Of-Publication', 'Publisher', 'Image-URL-S', 'Image-URL-M',
       'Image-URL-L'],
      dtype='object')

In [121]:
filtered_rating.head()

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
5,23768,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
7,28523,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
15,77940,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
16,81977,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...

In [125]:
y = filtered_rating.groupby('Book-Title').count()['Book-Rating'] >=50
famous_books = y[y].index

In [128]:
final_ratings = filtered_rating[filtered_rating['Book-Title'].isin(famous_books)]

In [130]:
final_ratings.duplicated().sum()

0

In [131]:
pt = final_ratings.pivot_table(index = 'Book-Title' , columns='User-ID', values = 'Book-Rating')

In [132]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [133]:
pt.fillna(0, inplace=True)

In [134]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [135]:
# Now we will assume each book in a 810 dimensional field and then find Eucledian distance bewteen all books

In [136]:
from sklearn.metrics.pairwise import cosine_similarity

In [138]:
similarity_score = cosine_similarity(pt)

In [143]:
np.where(pt.index=='You Belong To Me')[0][0]

702

In [168]:
sorted(list(enumerate(similarity_score[9])), reverse=True , key=lambda x:x[1])

[(9, 0.9999999999999999),
 (551, 0.23187135338750886),
 (477, 0.223834869259762),
 (485, 0.22236326784034427),
 (184, 0.21887650488669838),
 (645, 0.20566041499879859),
 (215, 0.1975070669099261),
 (671, 0.19375923295294267),
 (584, 0.1920997843945783),
 (696, 0.18762912100900866),
 (539, 0.1843816341480533),
 (327, 0.18384161659754908),
 (183, 0.18249928360181683),
 (526, 0.18232473797502874),
 (242, 0.17920134700922877),
 (50, 0.17169504114514483),
 (42, 0.17083080558416086),
 (608, 0.17048875020616655),
 (678, 0.17012555248423897),
 (702, 0.16992694636714176),
 (469, 0.16966893060548507),
 (621, 0.16739702393950182),
 (466, 0.1665911054771005),
 (162, 0.15903814186510215),
 (541, 0.15898212714987553),
 (16, 0.15837878964578572),
 (692, 0.1536327428900351),
 (641, 0.15233939720121792),
 (515, 0.1516642132531828),
 (214, 0.15012696384214474),
 (113, 0.14803508352939102),
 (392, 0.14697896573037525),
 (576, 0.14559921547928192),
 (175, 0.1435685072155108),
 (246, 0.14178535765175948),
 (527, 0.1411541111130832),
 (400, 0.13932397164014543),
 (409, 0.13918988522201625),
 (100, 0.13833579305708113),
 (254, 0.13789815231810548),
 (646, 0.13783513512587192),
 (281, 0.13734098714005122),
 (598, 0.13551108017141766),
 (632, 0.13531413531901135),
 (510, 0.13402056203342386),
 (142, 0.13398624618033708),
 (85, 0.13346751306486804),
 (479, 0.1332149726057591),
 (290, 0.1323745727760555),
 (631, 0.13235357548664628),
 (369, 0.13091099224365385),
 (447, 0.12818143307693344),
 (87, 0.12533552709413615),
 (25, 0.12437820565878147),
 (156, 0.12341333573296269),
 (370, 0.12326324190302146),
 (49, 0.12292896937754208),
 (440, 0.12291248308013275),
 (566, 0.12169680846915991),
 (276, 0.12018571021571113),
 (605, 0.11995925675954318),
 (511, 0.11995906857084976),
 (18, 0.11841588736111816),
 (367, 0.1178338526773861),
 (230, 0.11700284854653026),
 (105, 0.11645277519346595),
 (24, 0.11641906088827643),
 (537, 0.11585350871190311),
 (675, 0.11432151866197995),
 (177, 0.11380233443497198),
 (432, 0.1135964626877009),
 (88, 0.11204071552463848),
 (410, 0.11190446262791684),
 (66, 0.11139995645487953),
 (64, 0.11088630656368792),
 (548, 0.11059075004548691),
 (554, 0.11046752101495175),
 (656, 0.11002179853042922),
 (115, 0.10967087717145121),
 (307, 0.10963607174345298),
 (604, 0.10935564554988858),
 (639, 0.10868322910373429),
 (648, 0.10854645236006462),
 (302, 0.10843758453572083),
 (170, 0.10531899994493345),
 (530, 0.10514869956460604),
 (157, 0.10438565383011933),
 (434, 0.1039195558318945),
 (636, 0.10361693153362367),
 (494, 0.10339322327975695),
 (622, 0.10337312665099455),
 (455, 0.10274919511683925),
 (525, 0.10269998541089753),
 (424, 0.10253232795507942),
 (465, 0.1017184571535518),
 (418, 0.10163623695745655),
 (146, 0.10082773073040821),
 (488, 0.10033219534198057),
 (657, 0.10018802474798927),
 (462, 0.09996211638135688),
 (459, 0.09952659728285311),
 (195, 0.09952248518212568),
 (227, 0.09924687970634358),
 (167, 0.09879701902825669),
 (350, 0.0987948678297321),
 (546, 0.09833572850398979),
 (524, 0.0982073807505708),
 (75, 0.09793926154799451),
 (686, 0.09775022336468756),
 (116, 0.09751156588868969),
 (78, 0.09742258081400511),
 (304, 0.09559846297318707),
 (314, 0.09558828098030267),
 (10, 0.09557405173825534),
 (403, 0.09437925213672001),
 (194, 0.09406767380333828),
 (72, 0.09383148632568364),
 (677, 0.09308645170702169),
 (235, 0.09298518731114401),
 (426, 0.09223305981075441),
 (581, 0.09132609092780458),
 (427, 0.0908418883069738),
 (211, 0.08999546909217507),
 (637, 0.08996195122542884),
 (77, 0.08983242232761456),
 (615, 0.0896407225071351),
 (288, 0.08939228265749509),
 (691, 0.08939228265749508),
 (286, 0.0892264983879902),
 (577, 0.08909493576188793),
 (431, 0.08851988652746721),
 (650, 0.08851275289095437),
 (390, 0.08835615926620026),
 (595, 0.08810875578207909),
 (226, 0.08804442642287039),
 (321, 0.08797775855837409),
 (704, 0.08791739645277159),
 (528, 0.08778808267659402),
 (301, 0.08749831216303525),
 (668, 0.08730871646426866),
 (161, 0.0873004497676195),
 (412, 0.0872338851999854),
 (690, 0.08630507992992323),
 (364, 0.08606793636207496),
 (679, 0.08603792069754687),
 (522, 0.08602486470349764),
 (63, 0.08597648629605154),
 (20, 0.08571983949572247),
 (396, 0.08565603610802411),
 (341, 0.08546547739343036),
 (143, 0.08501502839876024),
 (356, 0.08459272171363907),
 (573, 0.08458062579856329),
 (22, 0.0828520908110296),
 (257, 0.08239038171504899),
 (186, 0.08231067524312509),
 (415, 0.08194381809194014),
 (148, 0.0817223565448261),
 (558, 0.08125662218088622),
 (318, 0.08086868274730016),
 (471, 0.08042698827915741),
 (353, 0.08012388505634097),
 (483, 0.07981504340066381),
 (81, 0.07980105706123247),
 (662, 0.07966163410448039),
 (27, 0.07965453358407729),
 (404, 0.07884146372507175),
 (12, 0.07861476876368761),
 (343, 0.07849279029850834),
 (489, 0.07835140923839562),
 (196, 0.0776407655183257),
 (311, 0.07763650162524846),
 (659, 0.07761904141338632),
 (164, 0.0775985630758499),
 (108, 0.0770932030839924),
 (397, 0.07687530248670736),
 (205, 0.07687154014492743),
 (491, 0.07684212591086631),
 (150, 0.07614057601896666),
 (44, 0.0758909296203281),
 (56, 0.07579153092673374),
 (676, 0.07526977074841561),
 (212, 0.07480913877817186),
 (173, 0.07477584641001424),
 (144, 0.07460499004767034),
 (506, 0.0741777161887128),
 (287, 0.07397418920692596),
 (129, 0.0736465266867487),
 (247, 0.07348644198151535),
 (470, 0.07316472466285726),
 (617, 0.07313433432939129),
 (474, 0.07302807896080914),
 (228, 0.07299342313012838),
 (282, 0.07292265708563146),
 (536, 0.07285751179037295),
 (457, 0.07252953359596062),
 (658, 0.07242336215444524),
 (701, 0.0723972186805046),
 (388, 0.07207912452591408),
 (138, 0.07202281941529842),
 (51, 0.0720032916542866),
 (53, 0.07150687279734433),
 (300, 0.07122123116119197),
 (320, 0.07120864072577031),
 (565, 0.07117869098388536),
 (34, 0.07090224577906165),
 (209, 0.07069139490187172),
 (540, 0.07065228872192081),
 (260, 0.0705707953345447),
 (563, 0.07043916537887517),
 (94, 0.07038220684669927),
 (206, 0.0703259685581772),
 (54, 0.07026602613510499),
 (262, 0.07005959763029018),
 (473, 0.06974138433829821),
 (333, 0.06969627833961296),
 (361, 0.06941474500386655),
 (550, 0.06935828269990509),
 (232, 0.06840561984140062),
 (674, 0.06820974550195083),
 (259, 0.06790677947220895),
 (168, 0.06739015275879734),
 (335, 0.06722491069789366),
 (241, 0.0670317469752395),
 (192, 0.06698978835694314),
 (592, 0.06676277356086213),
 (284, 0.0665735550588169),
 (312, 0.06604208441803797),
 (586, 0.06599405626157902),
 (589, 0.06550043890589927),
 (258, 0.06501377870696871),
 (130, 0.0642196329550959),
 (590, 0.06372155207058539),
 (13, 0.06359447424769016),
 (41, 0.06354549649649963),
 (132, 0.06334276804358722),
 (294, 0.06333833866241524),
 (323, 0.0625251580401569),
 (48, 0.06244733880580034),
 (487, 0.06241808572478563),
 (580, 0.062322718082034934),
 (303, 0.0619917622818848),
 (626, 0.061242006135882626),
 (36, 0.06094106079553633),
 (278, 0.0604108483758242),
 (245, 0.06036321632993141),
 (169, 0.06025528616965837),
 (96, 0.060170545829509),
 (313, 0.06005626953383734),
 (467, 0.05995995781558451),
 (256, 0.059175410847850114),
 (332, 0.05863745759568711),
 (165, 0.05847361972980306),
 (37, 0.05835234696933115),
 (29, 0.05813779699417635),
 (6, 0.05801279594406958),
 (379, 0.057231346468814975),
 (385, 0.05708043419036664),
 (178, 0.057047457417149755),
 (512, 0.05700514257086457),
 (128, 0.05682286025607014),
 (35, 0.05603931048944952),
 (224, 0.05596028229435464),
 (39, 0.05528730563201238),
 (705, 0.0547718935037416),
 (480, 0.05459492742854516),
 (495, 0.05431659759372597),
 (394, 0.054085173950894745),
 (26, 0.05398336024314232),
 (28, 0.05337454942042155),
 (638, 0.05324796835316568),
 (611, 0.05321412357035597),
 (250, 0.05262990766893706),
 (647, 0.05256943361318355),
 (68, 0.05235124659254644),
 (503, 0.051975413693454736),
 (610, 0.05190235073880491),
 (251, 0.05173119131024361),
 (549, 0.051476508266593404),
 (342, 0.05099151831470348),
 (279, 0.050984429365771716),
 (252, 0.050804160721453065),
 (476, 0.0506451281608536),
 (90, 0.050575494196361544),
 (579, 0.050264833255936975),
 (263, 0.049605827067189204),
 (231, 0.04938933853022259),
 (660, 0.04864323032907135),
 (152, 0.04815133187010549),
 (453, 0.04812093551316311),
 (365, 0.04789877444274667),
 (420, 0.04771263860481823),
 (1, 0.04716094908854913),
 (423, 0.04712328494197348),
 (502, 0.04692359933378179),
 (437, 0.04688141875159205),
 (322, 0.046777395492685815),
 (59, 0.04556284165902919),
 (694, 0.04486003076513041),
 (125, 0.04470788933580421),
 (463, 0.044301250349845195),
 (655, 0.04362132428246816),
 (153, 0.043506293277938236),
 (84, 0.04342004270894518),
 (620, 0.042958189569852624),
 (139, 0.04280277158570711),
 (684, 0.04278850707001069),
 (2, 0.0416819540485443),
 (683, 0.041326749916064005),
 (182, 0.039607163732134944),
 (255, 0.039237283283857935),
 (505, 0.03918981216658769),
 (17, 0.03902453354707),
 (421, 0.03845585014701182),
 (377, 0.038362759112027),
 (582, 0.03801769961599412),
 (680, 0.037848817700369554),
 (0, 0.03667590746512177),
 (326, 0.034463006739257014),
 (547, 0.034143257538308394),
 (103, 0.03189365612614473),
 (578, 0.03142062805656218),
 (616, 0.030258488865004124),
 (216, 0.02925322122472898),
 (181, 0.02865599391033958),
 (517, 0.027984415620709423),
 (441, 0.027224421157107957),
 (112, 0.026935311051013076),
 (500, 0.025300708101730213),
 (218, 0.02287924835307935),
 (570, 0.01882550244132398),
 (3, 0.0),
 (4, 0.0),
 (5, 0.0),
 (7, 0.0),
 (8, 0.0),
 (11, 0.0),
 (14, 0.0),
 (15, 0.0),
 (19, 0.0),
 (21, 0.0),
 (23, 0.0),
 (30, 0.0),
 (31, 0.0),
 (32, 0.0),
 (33, 0.0),
 (38, 0.0),
 (40, 0.0),
 (43, 0.0),
 (45, 0.0),
 (46, 0.0),
 (47, 0.0),
 (52, 0.0),
 (55, 0.0),
 (57, 0.0),
 (58, 0.0),
 (60, 0.0),
 (61, 0.0),
 (62, 0.0),
 (65, 0.0),
 (67, 0.0),
 (69, 0.0),
 (70, 0.0),
 (71, 0.0),
 (73, 0.0),
 (74, 0.0),
 (76, 0.0),
 (79, 0.0),
 (80, 0.0),
 (82, 0.0),
 (83, 0.0),
 (86, 0.0),
 (89, 0.0),
 (91, 0.0),
 (92, 0.0),
 (93, 0.0),
 (95, 0.0),
 (97, 0.0),
 (98, 0.0),
 (99, 0.0),
 (101, 0.0),
 (102, 0.0),
 (104, 0.0),
 (106, 0.0),
 (107, 0.0),
 (109, 0.0),
 (110, 0.0),
 (111, 0.0),
 (114, 0.0),
 (117, 0.0),
 (118, 0.0),
 (119, 0.0),
 (120, 0.0),
 (121, 0.0),
 (122, 0.0),
 (123, 0.0),
 (124, 0.0),
 (126, 0.0),
 (127, 0.0),
 (131, 0.0),
 (133, 0.0),
 (134, 0.0),
 (135, 0.0),
 (136, 0.0),
 (137, 0.0),
 (140, 0.0),
 (141, 0.0),
 (145, 0.0),
 (147, 0.0),
 (149, 0.0),
 (151, 0.0),
 (154, 0.0),
 (155, 0.0),
 (158, 0.0),
 (159, 0.0),
 (160, 0.0),
 (163, 0.0),
 (166, 0.0),
 (171, 0.0),
 (172, 0.0),
 (174, 0.0),
 (176, 0.0),
 (179, 0.0),
 (180, 0.0),
 (185, 0.0),
 (187, 0.0),
 (188, 0.0),
 (189, 0.0),
 (190, 0.0),
 (191, 0.0),
 (193, 0.0),
 (197, 0.0),
 (198, 0.0),
 (199, 0.0),
 (200, 0.0),
 (201, 0.0),
 (202, 0.0),
 (203, 0.0),
 (204, 0.0),
 (207, 0.0),
 (208, 0.0),
 (210, 0.0),
 (213, 0.0),
 (217, 0.0),
 (219, 0.0),
 (220, 0.0),
 (221, 0.0),
 (222, 0.0),
 (223, 0.0),
 (225, 0.0),
 (229, 0.0),
 (233, 0.0),
 (234, 0.0),
 (236, 0.0),
 (237, 0.0),
 (238, 0.0),
 (239, 0.0),
 (240, 0.0),
 (243, 0.0),
 (244, 0.0),
 (248, 0.0),
 (249, 0.0),
 (253, 0.0),
 (261, 0.0),
 (264, 0.0),
 (265, 0.0),
 (266, 0.0),
 (267, 0.0),
 (268, 0.0),
 (269, 0.0),
 (270, 0.0),
 (271, 0.0),
 (272, 0.0),
 (273, 0.0),
 (274, 0.0),
 (275, 0.0),
 (277, 0.0),
 (280, 0.0),
 (283, 0.0),
 (285, 0.0),
 (289, 0.0),
 (291, 0.0),
 (292, 0.0),
 (293, 0.0),
 (295, 0.0),
 (296, 0.0),
 (297, 0.0),
 (298, 0.0),
 (299, 0.0),
 (305, 0.0),
 (306, 0.0),
 (308, 0.0),
 (309, 0.0),
 (310, 0.0),
 (315, 0.0),
 (316, 0.0),
 (317, 0.0),
 (319, 0.0),
 (324, 0.0),
 (325, 0.0),
 (328, 0.0),
 (329, 0.0),
 (330, 0.0),
 (331, 0.0),
 (334, 0.0),
 (336, 0.0),
 (337, 0.0),
 (338, 0.0),
 (339, 0.0),
 (340, 0.0),
 (344, 0.0),
 (345, 0.0),
 (346, 0.0),
 (347, 0.0),
 (348, 0.0),
 (349, 0.0),
 (351, 0.0),
 (352, 0.0),
 (354, 0.0),
 (355, 0.0),
 (357, 0.0),
 (358, 0.0),
 (359, 0.0),
 (360, 0.0),
 (362, 0.0),
 (363, 0.0),
 (366, 0.0),
 (368, 0.0),
 (371, 0.0),
 (372, 0.0),
 (373, 0.0),
 (374, 0.0),
 (375, 0.0),
 (376, 0.0),
 (378, 0.0),
 (380, 0.0),
 (381, 0.0),
 (382, 0.0),
 (383, 0.0),
 (384, 0.0),
 (386, 0.0),
 (387, 0.0),
 (389, 0.0),
 (391, 0.0),
 (393, 0.0),
 (395, 0.0),
 (398, 0.0),
 (399, 0.0),
 (401, 0.0),
 (402, 0.0),
 (405, 0.0),
 (406, 0.0),
 (407, 0.0),
 (408, 0.0),
 (411, 0.0),
 (413, 0.0),
 (414, 0.0),
 (416, 0.0),
 (417, 0.0),
 (419, 0.0),
 (422, 0.0),
 (425, 0.0),
 (428, 0.0),
 (429, 0.0),
 (430, 0.0),
 (433, 0.0),
 (435, 0.0),
 (436, 0.0),
 (438, 0.0),
 (439, 0.0),
 (442, 0.0),
 (443, 0.0),
 (444, 0.0),
 (445, 0.0),
 (446, 0.0),
 (448, 0.0),
 (449, 0.0),
 (450, 0.0),
 (451, 0.0),
 (452, 0.0),
 (454, 0.0),
 (456, 0.0),
 (458, 0.0),
 (460, 0.0),
 (461, 0.0),
 (464, 0.0),
 (468, 0.0),
 (472, 0.0),
 (475, 0.0),
 (478, 0.0),
 (481, 0.0),
 (482, 0.0),
 (484, 0.0),
 (486, 0.0),
 (490, 0.0),
 (492, 0.0),
 (493, 0.0),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0),
 (499, 0.0),
 (501, 0.0),
 (504, 0.0),
 (507, 0.0),
 (508, 0.0),
 (509, 0.0),
 (513, 0.0),
 (514, 0.0),
 (516, 0.0),
 (518, 0.0),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (523, 0.0),
 (529, 0.0),
 (531, 0.0),
 (532, 0.0),
 (533, 0.0),
 (534, 0.0),
 (535, 0.0),
 (538, 0.0),
 (542, 0.0),
 (543, 0.0),
 (544, 0.0),
 (545, 0.0),
 (552, 0.0),
 (553, 0.0),
 (555, 0.0),
 (556, 0.0),
 (557, 0.0),
 (559, 0.0),
 (560, 0.0),
 (561, 0.0),
 (562, 0.0),
 (564, 0.0),
 (567, 0.0),
 (568, 0.0),
 (569, 0.0),
 (571, 0.0),
 (572, 0.0),
 (574, 0.0),
 (575, 0.0),
 (583, 0.0),
 (585, 0.0),
 (587, 0.0),
 (588, 0.0),
 (591, 0.0),
 (593, 0.0),
 (594, 0.0),
 (596, 0.0),
 (597, 0.0),
 (599, 0.0),
 (600, 0.0),
 (601, 0.0),
 (602, 0.0),
 (603, 0.0),
 (606, 0.0),
 (607, 0.0),
 (609, 0.0),
 (612, 0.0),
 (613, 0.0),
 (614, 0.0),
 (618, 0.0),
 (619, 0.0),
 (623, 0.0),
 (624, 0.0),
 (625, 0.0),
 (627, 0.0),
 (628, 0.0),
 (629, 0.0),
 (630, 0.0),
 (633, 0.0),
 (634, 0.0),
 (635, 0.0),
 (640, 0.0),
 (642, 0.0),
 (643, 0.0),
 (644, 0.0),
 (649, 0.0),
 (651, 0.0),
 (652, 0.0),
 (653, 0.0),
 (654, 0.0),
 (661, 0.0),
 (663, 0.0),
 (664, 0.0),
 (665, 0.0),
 (666, 0.0),
 (667, 0.0),
 (669, 0.0),
 (670, 0.0),
 (672, 0.0),
 (673, 0.0),
 (681, 0.0),
 (682, 0.0),
 (685, 0.0),
 (687, 0.0),
 (688, 0.0),
 (689, 0.0),
 (693, 0.0),
 (695, 0.0),
 (697, 0.0),
 (698, 0.0),
 (699, 0.0),
 (700, 0.0),
 (703, 0.0)]

In [176]:
def recommender(book_name):
    index = np.where(pt.index==book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_score[9])), reverse=True , key=lambda x:x[1])[1:6]


    for i in similar_items:
        print(pt.index[i[0]])

In [177]:
recommender('1984')

The Hours : A Novel
The Amber Spyglass (His Dark Materials, Book 3)
The Blind Assassin
Falling Angels
Three Junes